microclimate-dev2ops/microclimate-eclipse-tools

dev/gradle.properties
=> Issue #16: Disable org.gradle.daemon

dev/ant_build/build-mdt.xml, dev/com.ibm.microclimate/feature.xml, dev/gradle.properties
=> Issue #18: Version update

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnection.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/constants/MCConstants.java
Fixes #21 
Support new Microclimate validate and validate generate APIs.
=> Issue #21: Support new Microclimate validation APIs

dev/com.ibm.microclimate.base/feature.xml, dev/com.ibm.microclimate.core/META-INF/MANIFEST.MF, dev/com.ibm.microclimate.test/META-INF/MANIFEST.MF, dev/com.ibm.microclimate.ui/META-INF/MANIFEST.MF, dev/com.ibm.microclimate/feature.xml
Fixes #27 
Update the plugin and feature versions for the 19.01 release.
=> Issue #27: update plugin and feature versions for 19.01 release

dev/com.ibm.microclimate.core/plugin.properties, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnection.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/constants/MCConstants.java, dev/com.ibm.microclimate.ui/plugin.properties, dev/com.ibm.microclimate.ui/plugin.xml, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/OpenMicroclimateUIAction.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/messages.properties
Fixes #24 
Add an action on a Microclimate connection to open the Microclimate UI at the import project page.
=> Issue #24: Add open import project page action

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnection.java, dev/com.ibm.microclimate.test/src/com/ibm/microclimate/test/BaseAutoBuildTest.java, dev/com.ibm.microclimate.test/src/com/ibm/microclimate/test/BaseValidationTest.java, dev/com.ibm.microclimate.test/src/com/ibm/microclimate/test/MicroclimateTests.java
Fixes #31 
- Fix up LibertyDebugTest based on changes to Microclimate
- Make base test cases abstract
- Create a test list
=> Issue #31: Update LibertyDebugTest

dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/messages.properties
Fixes #33 
Fix the no projects message to match the menu item text.
=> Issue #33: fix no projects message to match the menu item

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/MicroclimateCorePlugin.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/IDebugLauncher.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MCEclipseApplication.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/constants/ProjectCapabilities.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/messages/Messages.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/messages/messages.properties, dev/com.ibm.microclimate.ui/META-INF/MANIFEST.MF, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/MicroclimateUIPlugin.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/AttachDebuggerAction.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/RestartDebugModeAction.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/debug/NodeJSDebugLauncher.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/debug/NodeJsBrowserDialog.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/debug/WebBrowserSelectionDialog.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/Messages.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/messages.properties, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/prefs/MicroclimatePrefsParentPage.java
Fixes #35 
Add support for debugging Node.js projects.
=> Issue #35: Add support for debugging Node.js projects

dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/debug/NodeJsBrowserDialog.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/debug/WebBrowserSelectionDialog.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/messages.properties, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/prefs/MicroclimatePrefsParentPage.java
Fixes #39 
Improve the dialogs and preference page for Node.js debug.
=> Issue #39: Improve Node.js debug dialogs and preferences

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateApplicationFactory.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnection.java
Fixes #42 
Remove projects that are not in the list returned by Microclimate on a refresh.
=> Issue #42: remove projects that are not in the list on a refresh

dev/com.ibm.microclimate.base/feature.xml, dev/com.ibm.microclimate.core/META-INF/MANIFEST.MF, dev/com.ibm.microclimate.ui/META-INF/MANIFEST.MF, dev/com.ibm.microclimate/feature.xml
Fixes #44 
Update plugin and feature versions for 19.02.
=> Issue #44: Update plugin and feature versions for 19.02

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnection.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateSocket.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/console/SocketConsole.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/constants/MCConstants.java
Fixes #46 
Add the socket namespace to the URI
=> Issue #46: Add socket namespace to the URI

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateSocket.java
Fixes #52 
Refresh the project on a restart event to ensure the mode is correct.
=> Issue #52: Refresh the project on a restart event to ensure the mode is correct

dev/ant_build/build-mdt.xml, dev/com.ibm.microclimate.base/feature.xml, dev/com.ibm.microclimate.core/META-INF/MANIFEST.MF, dev/com.ibm.microclimate.ui/META-INF/MANIFEST.MF, dev/com.ibm.microclimate/feature.xml
=> Version updates for 19.03

dev/ant_build/build-mdt.xml, dev/com.ibm.microclimate/feature.xml
=> Issue #65: Version update to 19.04

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/HttpUtil.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/ICPSyncManager.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/remote/APIUtils.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/remote/AbstractDevice.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/remote/HostDevice.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/remote/ICPDevice.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/remote/Syncthing.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/remote/SyncthingEventMonitor.java
- Improve ICP cleanup code
- Add a rescan method for folders
- Add comments
=> Add ICP cleanup code

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/ICPMicroclimateConnection.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/LocalMicroclimateConnection.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnection.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnectionManager.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/SWTUtil.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/Messages.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/messages.properties, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/ConnectionComposite.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/ICPConnectionComposite.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/LocalConnectionComposite.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/NewMicroclimateConnectionPage.java
- Update new connection wizard to allow user to select the connection type
- Fixed problems with validation for local connection
- Fixed unnecessary Next button showing in wizard
=> ICP: Update new connection wizard for ICP

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MCEclipseApplication.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateApplication.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateApplicationFactory.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateObjectFactory.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateSocket.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/constants/MCConstants.java
=> Issue #82: Support custom context root

dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/DeleteProjectAction.java
=> Issue #93: Enable project delete regardless of project state

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateApplication.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateSocket.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/HideAllLogsAction.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/LogFileActionProvider.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/ShowAllLogsAction.java
Fixes #99
-  Problem deleting a project right after it is created, need to make sure the UI is refreshed
-  Problems with the log file actions getting NPEs
=> Issue #99: Fix post project creation issues

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/IOperationHandler.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnection.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateSocket.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/Messages.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/messages.properties, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/NewMicroclimateProjectPage.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/NewMicroclimateProjectWizard.java
=> Issue #95: Import project into Eclipse on project create

dev/com.ibm.microclimate.test/src/com/ibm/microclimate/test/BaseTest.java, dev/com.ibm.microclimate.test/src/com/ibm/microclimate/test/util/MicroclimateUtil.java
=> Issue #105: Update the test cases for the new log files

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MCUtil.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/DeleteProjectAction.java
Fixes #107
Use files to compare instead of paths so that it works on Windows.
=> Issue #107: Use files to compare instead of paths

dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/views/ViewHelper.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/NewMicroclimateProjectWizard.java
=> Issue #109: Expand the connection in the view on project create

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/console/SocketConsole.java, dev/com.ibm.microclimate.ui/plugin.xml, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/console/ShowOnContentChangeAction.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/console/SocketConsolePageParticipant.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/Messages.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/messages.properties
Fixes #111
Add a show on content change action to the toolbar for all Microclimate project consoles.
=> Issue #111: Add a show on content change action to the console toolbar

dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/Messages.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/messages/messages.properties, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/NewMicroclimateProjectPage.java
Fixes #116 
Add a read only text 'label' before the group.
=> Issue #116: Fix accessibility for project template group

dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/wizards/NewMicroclimateProjectPage.java
=> Issue #117: Fix the template table column colours in the new project wizard

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateApplication.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateConnection.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/connection/MicroclimateSocket.java
=> Issue #120: Update project log support

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateApplicationFactory.java
=> Issue #114: Update the state of the application (open or closed)

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateApplication.java, dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/MicroclimateApplicationFactory.java, dev/com.ibm.microclimate.ui/src/com/ibm/microclimate/ui/internal/actions/AttachDebuggerAction.java
=> Issue #124: Don't continue with update if project is disabled

dev/build.gradle
=> update output file name

dev/com.ibm.microclimate.core/src/com/ibm/microclimate/core/internal/HttpUtil.java
=> Issue #155: Set the read timeout explicitly in HttpUtil
